### ISSUE TITLE
Fill all States

### ISSUE THREAD

**Issue by tarek903** [amratab/FlexibleSteppedProgressBar#1]
hi Amrata,

i was wondering is there a way to fill all states till the last one (currently fill all before current Index)

thanks in advance

**Comment by amratab** [comment]
You can mark the last point as completedTillIndex to fill it.
progressBar.numberOfPoints = 5
progressBar.completedTillIndex = 4

**Comment by tarek903** [comment]
@amratab still doesn't fill the last state 

progressBarWithoutLastState.numberOfPoints = 4
progressBarWithoutLastState.completedTillIndex = 3


![screen shot 2017-01-16 at 8 07 26 pm](https://cloud.githubusercontent.com/assets/11038057/21994269/8cb9cd1e-dc27-11e6-9287-ecbf6d618d00.png)

**Comment by amratab** [comment]
Can you briefly explain what is your exact requirement. Do you want all the circles to be filled and look same and not indicate the last state differently? If thats the case, give same values for progressRadius and radius and define lastStateOuterCircleLineWidth as 0.
progressBar.radius = 25
progressBar.progressRadius = 25 
progressBar.lastStateOuterCircleLineWidth = 0

But if you do need to show the last state differently later, then I don't think there is a way to show them all filled in the beginning without showing last one separately.

**Comment by tarek903** [comment]
ok i got it, thanks alot really grateful for your answering time ,hope you all the best
