### ISSUE TITLE
didSelectItemAtIndex() delegate not fired after setting current index

### ISSUE THREAD

**Issue by aliasdoc** [amratab/FlexibleSteppedProgressBar#2]
Hi, for first, good job !

I just see that `didSelectItemAtIndex()`  delegate method is not fired after setting current index, just need to call in setter

```swift

FlexibleSteppedProgressBar.swift

/// The current selected index
    open var currentIndex: Int = 0 {
        willSet(newValue){
            if let delegate = self.delegate {
                delegate.progressBar?(self, willSelectItemAtIndex: newValue)
            }
        }
        didSet {
//            animationRendering = true
            self.setNeedsDisplay()
            if let delegate = self.delegate {
                delegate.progressBar?(self, didSelectItemAtIndex: currentIndex)
            }
        }
    }

```

**Comment by amratab** [comment]
thanks! Do you mean its not getting called from your code? Can you please show me the initialization code you have used?

**Comment by aliasdoc** [comment]
Hi @amratab, I'm doing this way:

```swift
self.masterViewController.stepView.currentIndex = 1
self.masterViewController.stepView.completedTillIndex = 1

```

**Comment by amratab** [comment]
I am sorry for replying so late. 
You have to set delegate inside your controller as showed in the README.
progressBar.delegate = self
In your case, I guess
self.masterViewController.stepView.delegate = self.masterViewController
