### ISSUE TITLE
Hide top and bottom label

### ISSUE THREAD

**Issue by prakashtripathi** [amratab/FlexibleSteppedProgressBar#23]
Hii, 
I'm working on a project where only need FlexibleSteppedProgressBar but not label which is shown at top and bottom. can you suggest how to customize it?  

I need something like below one
![img_0638](https://user-images.githubusercontent.com/23715445/49583791-447cea00-f97f-11e8-9cea-fbce2a750ad2.JPG)

**Comment by mihailsalari** [comment]
Add a property in FlexibleSteppedProgressBar.swift: 
open var isTopTextHidden: Bool = false {
    didSet {
      setNeedsDisplay()
    }
  }

then in draw rect method, replace:
 renderBottomTextIndexes()
    renderTextIndexes()
renderTopTextIndexes()

with:
if isTopTextHidden {
      // Add logic
    } else {
      renderTopTextIndexes()
    }
    
    renderBottomTextIndexes()
    renderTextIndexes()


and in your controller call with:
progressBarWithoutLastState.isTopTextHidden = true

That's it.
