### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by hgado11** [amratab/FlexibleSteppedProgressBar#27]
which branch support Swift4.2?

**Comment by mcleinman** [comment]
The `master` branch is compatible with Swift 4.2. There is an issue with the tagging of `0.6.0`.

It looks like the code for version `0.6.0` - including the update to Swift 4.2 -  was [done after the tag was created](https://github.com/amratab/FlexibleSteppedProgressBar/compare/0.6.0...master). Thus the code that cocoapods pulls is essentially actually `0.5.0`.

We may need a new `0.6.1` tag and podspec update at this point, as `0.6.0` has been used.

**Comment by amratab** [comment]
I will fix this and close this issue. Thanks for informing me about the issue @mcleinman.

**Comment by amratab** [comment]
Updated the tag. @mcleinman Please verify and close.

**Comment by mcleinman** [comment]
Looks great. Thank you!
