### ISSUE TITLE
Set stepText indices font?

### ISSUE THREAD

**Issue by domifab** [amratab/FlexibleSteppedProgressBar#32]
Is it possible to set a font for the indices only? I don't set a font at all and get this Warning -> 

> CoreText performance note: Client called CTFontCreateWithName() using name ".SFUI-Semibold" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.

**Comment by abdulla-allaith** [comment]
+1

**Comment by abdulla-allaith** [comment]
@domifab I believe this was fixed in the latest release using a new attribute: `centerLayerTextFont`.
I am using the new attribute and the center indices font is customizable!

@amratab possibly close this issue? 👍
