### ISSUE TITLE
Step text into 2 lines???

### ISSUE THREAD

**Issue by stvding** [amratab/FlexibleSteppedProgressBar#7]
I set the text to "Order\ndelivered" with a "\n" newline in between. but it only shows "Order" not "delivered" on the second line. Can you support that??

**Comment by marknf94** [comment]
Any progress on this? Have the same request.

**Comment by john23591** [comment]
Hi, have any progress on this? I also need the same request....

**Comment by amratab** [comment]
No plan to implement this as of now.

**Comment by stvding** [comment]
My workaround is to change the libaray. Make the frame of the label’height twice. Then use \n in the text

**Comment by amratab** [comment]
@stvding Can you submit a pull request for the same?

**Comment by stvding** [comment]
@amratab i am not sure what you mean. Do u want me to provide my workaround in code??

**Comment by amratab** [comment]
@stvding If you want the library to include your change, you can code it and submit it here and I will merge it in the library code.

**Comment by john23591** [comment]
@stvding @amratab 
Please submit the change and merge it...tqvm...

**Comment by john23591** [comment]
Hi, have any update for this request?

**Comment by john23591** [comment]
Hi, may I know the status for this topic?

**Comment by amratab** [comment]
There is no plan to implement this.
