### ISSUE TITLE
Progress bar disappears but the text remains

### ISSUE THREAD

**Issue by vegidio** [amratab/FlexibleSteppedProgressBar#8]
Hi,

I created a progress bar with 4 points (`progressBar.numberOfPoints = 4`), but later I want to change this existing progress bar to 1 point (`progressBar.numberOfPoints = 1`).

The problem is, when I try to change to number of points from 4 to 1, the points disappear, but their texts remain. Following screenshots:

Initially, with 4 points:
<img width="294" alt="4 steps" src="https://user-images.githubusercontent.com/934172/28889058-186aa888-77c3-11e7-8ea8-a2012fa7eeaa.png">

After `progressBar.numberOfPoints = 1`, with 1 point:
<img width="289" alt="1 step" src="https://user-images.githubusercontent.com/934172/28889057-18669004-77c3-11e7-9056-a871dc695f13.png">

This is the code in my delegate:

```swift
    func progressBar(_ progressBar: FlexibleSteppedProgressBar, textAtIndex index: Int,
                     position: FlexibleSteppedProgressBarTextLocation) -> String {

        if position == FlexibleSteppedProgressBarTextLocation.bottom {
            switch index {
            case 0: return "BOOKED"
            case 1: return "ON THE WAY"
            case 2: return "SERVICING"
            case 3: return "COMPLETED"
            default: return "NONE"
            }
        }

        return ""
    }
```

How can I make the text under the points disappear as well when I go from 4 to 1 points?

**Comment by amratab** [comment]
Hi Vinícius,
Let me try this myself and I will let you know the solution.

**Comment by vegidio** [comment]
I found a workaround for this problem. I removed all `CATextLayer` objects from the view sublayers:

```swift
progressBar.layer.sublayers?.forEach({ layer in
    if layer.isKind(of: CATextLayer.self) {
        layer.removeFromSuperlayer()
    }
})
```

**Comment by vegidio** [comment]
Hi, is there any update on this? My workaround works, but it would be nice if the lib handled the removal of the sublayers when they are no longer needed, instead of making the development handle them separately :)
